version: '3.1'

services:
  nginx:
    container_name: nginx-proxy
    image: nginx:1.23
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443

  ho-vault:
    container_name: ho-vault
    image: vault:1.13.1
    ports:
      - 8200:8200
    volumes:
      - ./configs/vault/logs:/vault/logs
      - ./configs/vault/file:/vault/file
      - ./configs/vault:/vault/config
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json